// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table profile {
  id "bigint unsigned" [primary key, increment]
  name varchar [not null]
  about varchar
  photo varchar
  city varchar [not null]
}

Table interest {
  id "bigint unsigned" [primary key, increment]
  name varchar [not null, unique]
}

Table post {
  id "bigint unsigned" [primary key, increment]
  body text [not null, note: 'Content of the post']
  profile_id integer [not null, ref: > profile.id]
  like_counter integer
  view_counter integer

  indexes {
    (profile_id) [name: 'post_profile_id_idx']
  }
}

Table media {
  id "bigint unsigned" [primary key, increment]
  post_id integer [not null, ref: > post.id]
  type media_type [not null]

  indexes {
    (post_id) [name: 'media_post_id_idx']
  }
}

Table hashtag {
  id "bigint unsigned" [primary key, increment]
  name varchar [unique, not null]
}

Table profile_interest {
  id "bigint unsigned" [primary key, increment]
  profile_id "bigint unsigned" [not null, ref: > profile.id]
  interest_id "bigint unsigned" [not null, ref: > interest.id]

  indexes {
    (interest_id, profile_id) [name: 'profile_interest_interest_id_profile_id_unq', unique]
  }
}

Table post_hashtag {
  id "bigint unsigned" [primary key, increment]
  hashtag_id "bigint unsigned" [not null, ref: > hashtag.id]
  post_id "bigint unsigned" [not null, ref: > post.id]

  indexes {
    (post_id, hashtag_id) [name: 'post_hashtag_post_id_hashtag_id_unq', unique]
  }
}

Table chat {
  id "bigint unsigned" [primary key, increment]
  name varchar [not null]
}

Table chat_profile {
  id integer [primary key, unique]
  profile_id integer [not null, ref: > profile.id]
  chat_id integer [not null, ref: > chat.id]

  indexes {
    (profile_id, chat_id) [unique, name: 'chat_profile_profile_id_chat_id_unq']
  }
}

Enum media_type {
  audio
  video
  document
  image
}