// AP or AC system
// Routing: coordinator
// Sharding strategy: linear hash sharding (hybrid between hash and range sharding)
// Resharding type: consistency hashing
// Eventual consistency

// replication factor = 2
// consistency level - ONE (eventual consistency) or QUORUM (consistency)

Table messages.message {
  day int [not null]
  id bigint [not null]
  chat_id integer [not null]
  chat_name integer [not null]
  profile_id integer [not null]
  body varchar [not null]
  read_at timestamp
  created_at timestamp

  indexes {
    (part_key, chat_id, created_at) [pk]
  }
}

Table messages.comment {
  day int [not null]
  id bigint [not null]
  post_id integer [not null]
  profile_id integer [not null]
  body varchar [not null]
  created_at timestamp

  indexes {
    (day, chat_id, created_at) [pk]
  }
}